// flow-typed signature: 710610deef9b00b7cec0c317c9209c44
// flow-typed version: <<STUB>>/pouchdb-find_v^6.4.3/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pouchdb-find'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pouchdb-find' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pouchdb-find/lib/index-browser.es' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/index-browser' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/index.es' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pouchdb-find/lib/index-browser.es.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/index-browser.es'>;
}
declare module 'pouchdb-find/lib/index-browser.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/index-browser'>;
}
declare module 'pouchdb-find/lib/index.es.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/index.es'>;
}
declare module 'pouchdb-find/lib/index.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/index'>;
}
