// flow-typed signature: 9f1b7fe8b1c8cf259662fbdf63e38d4a
// flow-typed version: <<STUB>>/redux-pouchdb_v^0.1.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-pouchdb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-pouchdb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-pouchdb/lib/index' {
  declare module.exports: any;
}

declare module 'redux-pouchdb/lib/load' {
  declare module.exports: any;
}

declare module 'redux-pouchdb/lib/save' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-pouchdb/lib/index.js' {
  declare module.exports: $Exports<'redux-pouchdb/lib/index'>;
}
declare module 'redux-pouchdb/lib/load.js' {
  declare module.exports: $Exports<'redux-pouchdb/lib/load'>;
}
declare module 'redux-pouchdb/lib/save.js' {
  declare module.exports: $Exports<'redux-pouchdb/lib/save'>;
}
